<a href="https://colab.research.google.com/github/yulbeom/portfolio/blob/main/%EC%9E%90%EC%97%B0%EC%96%B47.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 훈련데이터와 테스트데이터 만들기

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [ ]:
text = """경마장에 있는 말이 뛰고 있다
그의 말이 법이다
가는 말이 고와야 오는 말이 곱다
"""

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 12


In [ ]:
print(tokenizer.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [ ]:
sequences = list()
for line in text.split('\n'): # 줄바꿈 문자를 기준으로 문장 토큰화
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

In [ ]:
text.split('\n')

['경마장에 있는 말이 뛰고 있다', '그의 말이 법이다', '가는 말이 고와야 오는 말이 곱다', '']

In [ ]:
tokenizer.texts_to_sequences(['경마장에 있는 말이 뛰고 있다'])

[[2, 3, 1, 4, 5]]

In [ ]:
len(sequences)

11

In [ ]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


### 패딩(padding)

In [ ]:
max_length = max(len(i) for i in sequences)

In [ ]:
[len(i) for i in sequences]

[2, 3, 4, 5, 2, 3, 2, 3, 4, 5, 6]

##### max(len(i) for i in sequences) 를 풀어서 쓴 표현

In [ ]:
a = []
for i in sequences:
  a.append(len(i))

In [ ]:
sequences = pad_sequences(sequences, padding='pre', maxlen=max_length) # 앞을 0으로 채움

In [ ]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [ ]:
sequences = np.array(sequences)

In [ ]:
sequences

array([[ 0,  0,  0,  0,  2,  3],
       [ 0,  0,  0,  2,  3,  1],
       [ 0,  0,  2,  3,  1,  4],
       [ 0,  2,  3,  1,  4,  5],
       [ 0,  0,  0,  0,  6,  1],
       [ 0,  0,  0,  6,  1,  7],
       [ 0,  0,  0,  0,  8,  1],
       [ 0,  0,  0,  8,  1,  9],
       [ 0,  0,  8,  1,  9, 10],
       [ 0,  8,  1,  9, 10,  1],
       [ 8,  1,  9, 10,  1, 11]], dtype=int32)

In [ ]:
X = sequences[:,:-1]
y = sequences[:, -1]

In [ ]:
print(X)
print(y)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]
[ 3  1  4  5  1  7  1  9 10  1 11]


### 원 핫 인코딩

In [ ]:
y = to_categorical(y, num_classes=vocab_size)

In [ ]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [ ]:
X.shape

(11, 5)

In [ ]:
embedding_dim = 10
hidden_units = 32

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units)) # hidden state의 node 수를 줄이면 성능 저하, 늘리면 과적합
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.4642 - accuracy: 0.3636 - 1s/epoch - 1s/step
Epoch 2/200
1/1 - 0s - loss: 2.4514 - accuracy: 0.3636 - 7ms/epoch - 7ms/step
Epoch 3/200
1/1 - 0s - loss: 2.4382 - accuracy: 0.3636 - 6ms/epoch - 6ms/step
Epoch 4/200
1/1 - 0s - loss: 2.4247 - accuracy: 0.4545 - 5ms/epoch - 5ms/step
Epoch 5/200
1/1 - 0s - loss: 2.4108 - accuracy: 0.4545 - 7ms/epoch - 7ms/step
Epoch 6/200
1/1 - 0s - loss: 2.3963 - accuracy: 0.4545 - 8ms/epoch - 8ms/step
Epoch 7/200
1/1 - 0s - loss: 2.3813 - accuracy: 0.5455 - 5ms/epoch - 5ms/step
Epoch 8/200
1/1 - 0s - loss: 2.3655 - accuracy: 0.5455 - 5ms/epoch - 5ms/step
Epoch 9/200
1/1 - 0s - loss: 2.3491 - accuracy: 0.5455 - 6ms/epoch - 6ms/step
Epoch 10/200
1/1 - 0s - loss: 2.3319 - accuracy: 0.5455 - 7ms/epoch - 7ms/step
Epoch 11/200
1/1 - 0s - loss: 2.3138 - accuracy: 0.5455 - 12ms/epoch - 12ms/step
Epoch 12/200
1/1 - 0s - loss: 2.2949 - accuracy: 0.5455 - 8ms/epoch - 8ms/step
Epoch 13/200
1/1 - 0s - loss: 2.2750 - accuracy: 0.5455 - 8ms

In [ ]:
# model.predict('경마장에') -> 불가능

In [ ]:
encoded = tokenizer.texts_to_sequences(['경마장에'])[0]

In [ ]:
encoded

[2]

In [ ]:
encoded = pad_sequences([encoded], padding='pre', maxlen=5)

In [ ]:
encoded

array([[0, 0, 0, 0, 2]], dtype=int32)

In [ ]:
result = model.predict(encoded, verbose=1)

1/1 [==============================] - 0s 296ms/step


In [ ]:
result

array([[1.2917155e-03, 1.1714405e-01, 1.6430803e-03, 8.2645637e-01,
        3.0819587e-03, 7.7223862e-03, 1.0095346e-03, 1.5391017e-02,
        3.3253455e-03, 7.6737823e-03, 1.4644008e-02, 6.1682716e-04]],
      dtype=float32)

In [ ]:
len(result[0])

12

In [ ]:
sum(result[0]) # 거의 1에 근접

1.0000000718282536

In [ ]:
result = np.argmax(result, axis=1)

In [ ]:
result

array([3])

In [ ]:
tokenizer.word_index.items()

dict_items([('말이', 1), ('경마장에', 2), ('있는', 3), ('뛰고', 4), ('있다', 5), ('그의', 6), ('법이다', 7), ('가는', 8), ('고와야', 9), ('오는', 10), ('곱다', 11)])

In [ ]:
for i in tokenizer.word_index.items():
  print(i)

('말이', 1)
('경마장에', 2)
('있는', 3)
('뛰고', 4)
('있다', 5)
('그의', 6)
('법이다', 7)
('가는', 8)
('고와야', 9)
('오는', 10)
('곱다', 11)


In [ ]:
for word, index in tokenizer.word_index.items():
  print(word, index)

말이 1
경마장에 2
있는 3
뛰고 4
있다 5
그의 6
법이다 7
가는 8
고와야 9
오는 10
곱다 11


In [ ]:
for word, index in tokenizer.word_index.items():
  if index == result:
    break
print(word)

있는


In [ ]:
current_word = '경마장에'
current_word = current_word + ' ' + word

In [ ]:
current_word

'경마장에 있는'

In [ ]:
encoded = tokenizer.texts_to_sequences(['경마장에'])[0]

In [ ]:
encoded

[2]

In [ ]:
def sentence_generation(model, tokenizer, current_word, n):
  init_word = current_word
  sentence = ''

  for _ in range(n):
    encoded = tokenizer.texts_to_sequences([current_word])[0]
    encoded_pad = pad_sequences([encoded], padding='pre', maxlen=5)
    result = model.predict(encoded_pad, verbose=0)
    result = np.argmax(result, axis=1)
    for word, index in tokenizer.word_index.items():
      if index == result:
        break
    current_word = current_word + ' ' + word
    sentence = sentence + current_word
    sentence

In [ ]:
print(sentence_generation(model, tokenizer, '경마장에', 4))

None


In [ ]:
print(sentence_generation(model, tokenizer, '그의', 2))

None


In [ ]:
print(sentence_generation(model, tokenizer, '가는', 5))

None


##### 챗봇데이터 Question 열만 추출하여 생성 모델 구현하고 히든스테이트의 노드수, 임베딩 벡터 차원등을 수업 중 했던 값으로 시작해서 변경하여 정확도를 업데이트 해보자.
##### RNN을 LSTM으로도 변경해서 학습 후 결과 비교해 봅니다. Colab의 GPU,TPU를 활용

In [ ]:
import pandas as pd
df = pd.read_csv('ChatbotData.csv')

In [ ]:
df.head()

Q            A  label
0           12시 땡!   하루가 또 가네요.      0
1      1지망 학교 떨어졌어    위로해 드립니다.      0
2     3박4일 놀러가고 싶다  여행은 언제나 좋죠.      0
3  3박4일 정도 놀러가고 싶다  여행은 언제나 좋죠.      0
4          PPL 심하네   눈살이 찌푸려지죠.      0

In [ ]:
df = df['Q']
df

0                         12시 땡!
1                    1지망 학교 떨어졌어
2                   3박4일 놀러가고 싶다
3                3박4일 정도 놀러가고 싶다
4                        PPL 심하네
                  ...           
11818             훔쳐보는 것도 눈치 보임.
11819             훔쳐보는 것도 눈치 보임.
11820                흑기사 해주는 짝남.
11821    힘든 연애 좋은 연애라는게 무슨 차이일까?
11822                 힘들어서 결혼할까봐
Name: Q, Length: 11823, dtype: object

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df)
vocab_size = len(tokenizer.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 13399


In [ ]:
sequences = list()
for line in df: # 줄바꿈 문자를 기준으로 문장 토큰화
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

In [ ]:
sequences

array([[    0,     0,     0, ...,     0,  4646,  4647],
       [    0,     0,     0, ...,     0,  4648,   343],
       [    0,     0,     0, ...,  4648,   343,   448],
       ...,
       [    0,     0,     0, ...,    91, 13396,   112],
       [    0,     0,     0, ..., 13396,   112, 13397],
       [    0,     0,     0, ...,     0,   555, 13398]], dtype=int32)

In [ ]:
max_len = max(len(i) for i in sequences)

In [ ]:
max_len

15

In [ ]:
sequences_pad = pad_sequences(sequences, maxlen=max_len, padding='pre')

In [ ]:
sequences_pad

array([[    0,     0,     0, ...,     0,  4646,  4647],
       [    0,     0,     0, ...,     0,  4648,   343],
       [    0,     0,     0, ...,  4648,   343,   448],
       ...,
       [    0,     0,     0, ...,    91, 13396,   112],
       [    0,     0,     0, ..., 13396,   112, 13397],
       [    0,     0,     0, ...,     0,   555, 13398]], dtype=int32)

In [ ]:
sequences = np.array(sequences_pad)
X = sequences[:,:-1]
y = sequences[:, -1]

In [ ]:
print(y)

[ 4647   343   448 ...   112 13397 13398]


In [ ]:
y = to_categorical(y, num_classes=vocab_size)

In [ ]:
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


##### 모델 설계

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [ ]:
embedding_dim = 10
hidden_units = 32

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
958/958 - 13s - loss: 8.6897 - accuracy: 0.0134 - 13s/epoch - 14ms/step
Epoch 2/200
958/958 - 12s - loss: 8.0614 - accuracy: 0.0205 - 12s/epoch - 12ms/step
Epoch 3/200
958/958 - 12s - loss: 7.8185 - accuracy: 0.0235 - 12s/epoch - 13ms/step
Epoch 4/200
958/958 - 11s - loss: 7.6012 - accuracy: 0.0286 - 11s/epoch - 12ms/step
Epoch 5/200
958/958 - 12s - loss: 7.3893 - accuracy: 0.0335 - 12s/epoch - 13ms/step
Epoch 6/200
958/958 - 13s - loss: 7.1753 - accuracy: 0.0390 - 13s/epoch - 13ms/step
Epoch 7/200
958/958 - 15s - loss: 6.9666 - accuracy: 0.0460 - 15s/epoch - 16ms/step
Epoch 8/200
958/958 - 15s - loss: 6.7656 - accuracy: 0.0536 - 15s/epoch - 16ms/step
Epoch 9/200
958/958 - 13s - loss: 6.5697 - accuracy: 0.0611 - 13s/epoch - 13ms/step
Epoch 10/200
958/958 - 12s - loss: 6.3763 - accuracy: 0.0692 - 12s/epoch - 13ms/step
Epoch 11/200
958/958 - 12s - loss: 6.1872 - accuracy: 0.0806 - 12s/epoch - 12ms/step
Epoch 12/200
958/958 - 12s - loss: 6.0027 - accuracy: 0.0924 - 12s/epoch -

In [ ]:
def sentence_generation(model, tokenizer, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word
    sentence = ''

    # n번 반복
    for _ in range(n):
        # 현재 단어에 대한 정수 인코딩과 패딩
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        # 입력한 X(현재 단어)에 대해서 Y를 예측하고 Y(예측한 단어)를 result에 저장.
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)

        for word, index in tokenizer.word_index.items(): 
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면 break
            if index == result:
                break

        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        current_word = current_word + ' '  + word

        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word

    sentence = init_word + sentence
    return sentence